services:
  - type: web
    name: gaokao-share
    runtime: python
    buildCommand: ""
    startCommand: python3 server.py
    plan: free
    envVars:
      - key: PORT
        value: "5000"
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: "VictorGao666/my_CLYZ_reference"
      - key: GITHUB_BRANCH
        value: "main"
